Repository Trinity-Developers-Club/20DOOS_WEB, pull requests merged in 2022-10, with the labels that each got.

#9 adding ui design
  Samridhi_Yadav/.gitignore
  Samridhi_Yadav/README.md
  Samridhi_Yadav/Readme.md
  Samridhi_Yadav/images/bg-pattern-bottom-desktop.svg
  Samridhi_Yadav/images/bg-pattern-bottom-mobile.svg
  Samridhi_Yadav/images/bg-pattern-top-desktop.svg
  Samridhi_Yadav/images/bg-pattern-top-mobile.svg
  Samridhi_Yadav/images/favicon-32x32.png
  Samridhi_Yadav/images/icon-star.svg
  Samridhi_Yadav/images/image-anne.jpg
  Samridhi_Yadav/images/image-colton.jpg
  Samridhi_Yadav/images/image-irene.jpg
  Samridhi_Yadav/index.html
  Samridhi_Yadav/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Update dineout.html fixed UI design
  Karan Vaswani/Dineout Clone/dineout.html
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 TODO-APP by Rudransh Aggarwal
  Rudransh_Aggarwal/TODO-APP/README.md
  Rudransh_Aggarwal/TODO-APP/index.html
  Rudransh_Aggarwal/TODO-APP/main.js
  Rudransh_Aggarwal/TODO-APP/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Added Pricing panel project
  Sanskriti/Readme.md
  Sanskriti/app.css
  Sanskriti/icon1.png
  Sanskriti/icon2.png
  Sanskriti/icon3.png
  Sanskriti/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Added a GNU license
  LICENSE
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 Created CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 I have created Tesla Clone using ReactJS hoping it'll help REACTJS Learners!
  .DS_Store
  nishant-ai/.DS_Store
  nishant-ai/README.md
  nishant-ai/TeslaClone/.gitignore
  nishant-ai/TeslaClone/README.md
  nishant-ai/TeslaClone/package-lock.json
  nishant-ai/TeslaClone/package.json
  nishant-ai/TeslaClone/public/favicon.png
  nishant-ai/TeslaClone/public/images/accessories.jpg
  nishant-ai/TeslaClone/public/images/audio.jpg
  nishant-ai/TeslaClone/public/images/connected.jpg
  nishant-ai/TeslaClone/public/images/down-arrow.svg
  nishant-ai/TeslaClone/public/images/favicon.ico
  nishant-ai/TeslaClone/public/images/game.jpg
  nishant-ai/TeslaClone/public/images/logo.svg
  nishant-ai/TeslaClone/public/images/model-3.jpg
  nishant-ai/TeslaClone/public/images/model-s.jpg
  nishant-ai/TeslaClone/public/images/model-x.jpg
  nishant-ai/TeslaClone/public/images/model-y.jpg
  nishant-ai/TeslaClone/public/images/new-interior.jpg
  nishant-ai/TeslaClone/public/images/solar-panel.jpg
  nishant-ai/TeslaClone/public/images/solar-roof.jpg
  nishant-ai/TeslaClone/public/index.html
  nishant-ai/TeslaClone/public/logo192.png
  nishant-ai/TeslaClone/public/logo512.png
  nishant-ai/TeslaClone/public/manifest.json
  nishant-ai/TeslaClone/public/robots.txt
  nishant-ai/TeslaClone/src/App.css
  nishant-ai/TeslaClone/src/App.js
  nishant-ai/TeslaClone/src/App.test.js
  nishant-ai/TeslaClone/src/app/store.js
  nishant-ai/TeslaClone/src/components/Header.js
  nishant-ai/TeslaClone/src/components/Home.js
  nishant-ai/TeslaClone/src/components/Section.js
  nishant-ai/TeslaClone/src/features/car/carSlice.js
  nishant-ai/TeslaClone/src/index.css
  nishant-ai/TeslaClone/src/index.js
  nishant-ai/TeslaClone/src/logo.svg
  nishant-ai/TeslaClone/src/reportWebVitals.js
  nishant-ai/TeslaClone/src/setupTests.js
  nishant-ai/TeslaClone/yarn.lock
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Added Digital Clock
  Anmol_Pal Digital Clock/index.html
  Anmol_Pal Digital Clock/index.js
  Anmol_Pal Digital Clock/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 Netflix Single Page Clone --learning
  nishant-ai/.DS_Store
  nishant-ai/NetflixClone/README.md
  nishant-ai/NetflixClone/firebase.json
  nishant-ai/NetflixClone/live.app.link.txt
  nishant-ai/NetflixClone/package-lock.json
  nishant-ai/NetflixClone/package.json
  nishant-ai/NetflixClone/public/apple-touch-icon.png
  nishant-ai/NetflixClone/public/favicon.ico
  nishant-ai/NetflixClone/public/index.html
  nishant-ai/NetflixClone/public/logo.png
  nishant-ai/NetflixClone/public/manifest.json
  nishant-ai/NetflixClone/public/robots.txt
  nishant-ai/NetflixClone/src/App.css
  nishant-ai/NetflixClone/src/App.js
  nishant-ai/NetflixClone/src/Banner.css
  nishant-ai/NetflixClone/src/Banner.js
  nishant-ai/NetflixClone/src/Nav.css
  nishant-ai/NetflixClone/src/Nav.js
  nishant-ai/NetflixClone/src/Row.css
  nishant-ai/NetflixClone/src/Row.js
  nishant-ai/NetflixClone/src/axios.js
  nishant-ai/NetflixClone/src/index.css
  nishant-ai/NetflixClone/src/index.js
  nishant-ai/NetflixClone/src/reportWebVitals.js
  nishant-ai/NetflixClone/src/requests.js
  nishant-ai/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 connect four :) A Game
  connect four/app.js
  connect four/index.html
  connect four/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#36 added museum of candy project
  Sanskriti/app.css
  Sanskriti/gumball.png
  Sanskriti/hand2.png
  Sanskriti/index.html
  Sanskriti/lolli_icon.png
  Sanskriti/milk.png
  Sanskriti/patter.html.html
  Sanskriti/sprinkles.png
  Sanskriti/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#47 I have added my party Bill splitter
  ArunKumarSingh_bill-splitter/index.css
  ArunKumarSingh_bill-splitter/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#44 Added bmi calculator website
  Mobasshir_BMI/index.html
  Mobasshir_BMI/index.js
  Mobasshir_BMI/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 candy museum website
  CandyProject/app.css
  CandyProject/candy.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 add weather app
  Aditya_bhagat/README.md
  Aditya_bhagat/weather-app/index.html
  Aditya_bhagat/weather-app/index.js
  Aditya_bhagat/weather-app/master.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 Flipkart UI Clone Added
  ArunKumarSingh_FlipkartUIClone/Flipkart.jpg
  ArunKumarSingh_FlipkartUIClone/README.md
  ArunKumarSingh_FlipkartUIClone/flip1.png
  ArunKumarSingh_FlipkartUIClone/images/appliances.jpg
  ArunKumarSingh_FlipkartUIClone/images/beauty.jpg
  ArunKumarSingh_FlipkartUIClone/images/cards.png
  ArunKumarSingh_FlipkartUIClone/images/fashion.jpg
  ArunKumarSingh_FlipkartUIClone/images/grocery.jpg
  ArunKumarSingh_FlipkartUIClone/images/home.jpeg
  ArunKumarSingh_FlipkartUIClone/images/laptop.jpg
  ArunKumarSingh_FlipkartUIClone/images/mobiles.png
  ArunKumarSingh_FlipkartUIClone/images/refurbished.jpg
  ArunKumarSingh_FlipkartUIClone/images/sale.jfif
  ArunKumarSingh_FlipkartUIClone/images/toys.jpg
  ArunKumarSingh_FlipkartUIClone/images/travels.jfif
  ArunKumarSingh_FlipkartUIClone/images/tri.png
  ArunKumarSingh_FlipkartUIClone/index.html
  ArunKumarSingh_FlipkartUIClone/products/bags.png
  ArunKumarSingh_FlipkartUIClone/products/breif.jpeg
  ArunKumarSingh_FlipkartUIClone/products/decor.jfif
  ArunKumarSingh_FlipkartUIClone/products/gas.jpeg
  ArunKumarSingh_FlipkartUIClone/products/shirt.jpg
  ArunKumarSingh_FlipkartUIClone/products/shoos.jfif
  ArunKumarSingh_FlipkartUIClone/products/tshirt.jpg
  ArunKumarSingh_FlipkartUIClone/products/wall.jpg
  ArunKumarSingh_FlipkartUIClone/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Added Zen-Landing-Page folder
  Rudransh_Aggarwal/Zen-Landing-Page/README.md
  Rudransh_Aggarwal/Zen-Landing-Page/index.html
  Rudransh_Aggarwal/Zen-Landing-Page/main.js
  Rudransh_Aggarwal/Zen-Landing-Page/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#49 Resume generator
  README.md
  vivek_resume_generator/.vscode/settings.json
  vivek_resume_generator/Procfile
  vivek_resume_generator/README.md
  vivek_resume_generator/db.sqlite3
  vivek_resume_generator/manage.py
  vivek_resume_generator/requirements.txt
  vivek_resume_generator/resume_builder/__init__.py
  vivek_resume_generator/resume_builder/__pycache__/__init__.cpython-38.pyc
  vivek_resume_generator/resume_builder/__pycache__/__init__.cpython-39.pyc
  vivek_resume_generator/resume_builder/__pycache__/settings.cpython-38.pyc
  vivek_resume_generator/resume_builder/__pycache__/settings.cpython-39.pyc
  vivek_resume_generator/resume_builder/__pycache__/urls.cpython-38.pyc
  vivek_resume_generator/resume_builder/__pycache__/urls.cpython-39.pyc
  vivek_resume_generator/resume_builder/__pycache__/wsgi.cpython-38.pyc
  vivek_resume_generator/resume_builder/__pycache__/wsgi.cpython-39.pyc
  vivek_resume_generator/resume_builder/asgi.py
  vivek_resume_generator/resume_builder/settings.py
  vivek_resume_generator/resume_builder/urls.py
  vivek_resume_generator/resume_builder/wsgi.py
  vivek_resume_generator/resume_site/__init__.py
  vivek_resume_generator/resume_site/__pycache__/__init__.cpython-38.pyc
  vivek_resume_generator/resume_site/__pycache__/__init__.cpython-39.pyc
  vivek_resume_generator/resume_site/__pycache__/admin.cpython-38.pyc
  vivek_resume_generator/resume_site/__pycache__/admin.cpython-39.pyc
  vivek_resume_generator/resume_site/__pycache__/apps.cpython-39.pyc
  vivek_resume_generator/resume_site/__pycache__/models.cpython-38.pyc
  vivek_resume_generator/resume_site/__pycache__/models.cpython-39.pyc
  vivek_resume_generator/resume_site/__pycache__/urls.cpython-38.pyc
  vivek_resume_generator/resume_site/__pycache__/urls.cpython-39.pyc
  vivek_resume_generator/resume_site/__pycache__/views.cpython-38.pyc
  vivek_resume_generator/resume_site/__pycache__/views.cpython-39.pyc
  vivek_resume_generator/resume_site/admin.py
  vivek_resume_generator/resume_site/apps.py
  vivek_resume_generator/resume_site/migrations/0001_initial.py
  vivek_resume_generator/resume_site/migrations/0002_auto_20210304_2243.py
  vivek_resume_generator/resume_site/migrations/0003_auto_20210304_2251.py
  vivek_resume_generator/resume_site/migrations/0004_auto_20210304_2259.py
  vivek_resume_generator/resume_site/migrations/__init__.py
  vivek_resume_generator/resume_site/migrations/__pycache__/0001_initial.cpython-38.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0001_initial.cpython-39.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0002_auto_20210304_2243.cpython-38.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0002_auto_20210304_2243.cpython-39.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0003_auto_20210304_2251.cpython-38.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0003_auto_20210304_2251.cpython-39.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0004_auto_20210304_2259.cpython-38.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/0004_auto_20210304_2259.cpython-39.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/__init__.cpython-38.pyc
  vivek_resume_generator/resume_site/migrations/__pycache__/__init__.cpython-39.pyc
  vivek_resume_generator/resume_site/models.py
  vivek_resume_generator/resume_site/tests.py
  vivek_resume_generator/resume_site/urls.py
  vivek_resume_generator/resume_site/views.py
  vivek_resume_generator/runtime.txt
  vivek_resume_generator/static/css/index.css
  vivek_resume_generator/static/css/main.css
  vivek_resume_generator/templates/home_page.html
  vivek_resume_generator/templates/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#48 Added Vaibhav portfolio website
  .DS_Store
  Vaibhav_Vijay/README.md
  Vaibhav_Vijay/css/style.css
  Vaibhav_Vijay/images/Group 3.png
  Vaibhav_Vijay/images/activity_tracker.jpg
  Vaibhav_Vijay/images/blood_bank.jpg
  Vaibhav_Vijay/images/cover.jpg
  Vaibhav_Vijay/images/cover_mobile.jpg
  Vaibhav_Vijay/images/erp_system.jpg
  Vaibhav_Vijay/images/favicon.png
  Vaibhav_Vijay/images/java_quiz.jpg
  Vaibhav_Vijay/images/myPhoto2.webp
  Vaibhav_Vijay/images/myPhoto4.jpg
  Vaibhav_Vijay/images/product_landing_page.jpg
  Vaibhav_Vijay/images/travel_buddy.jpg
  Vaibhav_Vijay/index.html
  Vaibhav_Vijay/js/index.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#52 Added favicon to index.html
  index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#51 cart app with react
  cart-feature react anuj/.gitignore
  cart-feature react anuj/README.md
  cart-feature react anuj/package-lock.json
  cart-feature react anuj/package.json
  cart-feature react anuj/public/favicon.ico
  cart-feature react anuj/public/index.html
  cart-feature react anuj/public/logo192.png
  cart-feature react anuj/public/logo512.png
  cart-feature react anuj/public/manifest.json
  cart-feature react anuj/public/robots.txt
  cart-feature react anuj/src/App.css
  cart-feature react anuj/src/App.js
  cart-feature react anuj/src/App.test.js
  cart-feature react anuj/src/components/AddItem.js
  cart-feature react anuj/src/components/Footer.js
  cart-feature react anuj/src/components/Navbar.js
  cart-feature react anuj/src/components/Product.js
  cart-feature react anuj/src/components/ProductList.js
  cart-feature react anuj/src/index.css
  cart-feature react anuj/src/index.js
  cart-feature react anuj/src/logo.svg
  cart-feature react anuj/src/reportWebVitals.js
  cart-feature react anuj/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#55 added blog post design
  Dhruv/images/favicon-32x32.png
  Dhruv/images/icon-music.svg
  Dhruv/images/illustration-hero.svg
  Dhruv/images/index.html
  Dhruv/images/pattern-background-desktop.svg
  Dhruv/images/pattern-background-mobile.svg
  Dhruv/images/style.css
  Dhruv/index.html
  Dhruv/readme.md
  Dhruv/style.css
Labels: help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#56 added upgraded ui design
  Dhruv/images/design/active-states.jpg
  Dhruv/images/design/desktop-design.jpg
  Dhruv/images/design/desktop-preview.jpg
  Dhruv/images/design/mobile-design.jpg
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#61 added docs in blog website
  Dhruv/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#62 added description in food wedsite
  food_website/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#67 Added Whiteboard Code
  White Board/Online-WhiteBoard/README.md
  White Board/Online-WhiteBoard/index.html
  White Board/Online-WhiteBoard/online_Whiteboard.png
  White Board/Online-WhiteBoard/script.js
  White Board/Online-WhiteBoard/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#66 Added card game
  Ravi_Singh_Bajetha/Card Game/Photos/angryface.png
  Ravi_Singh_Bajetha/Card Game/Photos/coke.png
  Ravi_Singh_Bajetha/Card Game/Photos/coolface.png
  Ravi_Singh_Bajetha/Card Game/Photos/evilface.png
  Ravi_Singh_Bajetha/Card Game/Photos/feverface.png
  Ravi_Singh_Bajetha/Card Game/Photos/freezeface.png
  Ravi_Singh_Bajetha/Card Game/Photos/lco.png
  Ravi_Singh_Bajetha/Card Game/Photos/mindblownface.png
  Ravi_Singh_Bajetha/Card Game/Photos/sneezeface.png
  Ravi_Singh_Bajetha/Card Game/Photos/thinkingface.png
  Ravi_Singh_Bajetha/Card Game/Photos/vomitface.png
  Ravi_Singh_Bajetha/Card Game/index.html
  Ravi_Singh_Bajetha/Card Game/index.js
  Ravi_Singh_Bajetha/Card Game/styles.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#72 Added basic project on fetching an API
  Ravi_Singh_Bajetha/Basic_API_Fetch/Ravi.js
  Ravi_Singh_Bajetha/Basic_API_Fetch/index.html
  Ravi_Singh_Bajetha/Basic_API_Fetch/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#70 Added footer and modified navbar
  index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#81 added laoding animation
  site/loading animation/index.html
  site/loading animation/style.css
  site/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#82 added social master
  site/social-media-dashboard-master/README.md
  site/social-media-dashboard-master/images/favicon-32x32.png
  site/social-media-dashboard-master/images/icon-down.svg
  site/social-media-dashboard-master/images/icon-facebook.svg
  site/social-media-dashboard-master/images/icon-instagram.svg
  site/social-media-dashboard-master/images/icon-twitter.svg
  site/social-media-dashboard-master/images/icon-up.svg
  site/social-media-dashboard-master/images/icon-youtube.svg
  site/social-media-dashboard-master/index.html
  site/social-media-dashboard-master/main.js
  site/social-media-dashboard-master/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#85 added smartwatcg design
  Dhruv/SmartWatch-HTML-CSS--master/index.html
  Dhruv/SmartWatch-HTML-CSS--master/sparshCodesLogo.png
  Dhruv/SmartWatch-HTML-CSS--master/style.css
  Dhruv/SmartWatch-HTML-CSS--master/watch-face.webp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#86 added intagram ui
  Dhruv/instagram-profile-ui-clone-master/README.md
  Dhruv/instagram-profile-ui-clone-master/package-lock.json
  Dhruv/instagram-profile-ui-clone-master/package.json
  Dhruv/instagram-profile-ui-clone-master/public/favicon.ico
  Dhruv/instagram-profile-ui-clone-master/public/index.html
  Dhruv/instagram-profile-ui-clone-master/public/logo192.png
  Dhruv/instagram-profile-ui-clone-master/public/logo512.png
  Dhruv/instagram-profile-ui-clone-master/public/manifest.json
  Dhruv/instagram-profile-ui-clone-master/public/robots.txt
  Dhruv/instagram-profile-ui-clone-master/src/App.css
  Dhruv/instagram-profile-ui-clone-master/src/App.js
  Dhruv/instagram-profile-ui-clone-master/src/App.test.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/About.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/Highlights.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/PostGrid.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/Profile.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/ProfileButtons.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/ProfileDetails.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/Tabs.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/TopNav.js
  Dhruv/instagram-profile-ui-clone-master/src/Components/ViewDashboard.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/Grid.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/Guides.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/IGTV.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/Reels.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/Tags.js
  Dhruv/instagram-profile-ui-clone-master/src/assets/highlight1.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/highlight2.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/highlight3.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/highlight4.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/highlight5.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post1.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post2.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post3.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post4.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post5.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post6.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post7.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post8.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/post9.png
  Dhruv/instagram-profile-ui-clone-master/src/assets/scLogo.jpg
  Dhruv/instagram-profile-ui-clone-master/src/index.css
  Dhruv/instagram-profile-ui-clone-master/src/index.js
  Dhruv/instagram-profile-ui-clone-master/src/logo.svg
  Dhruv/instagram-profile-ui-clone-master/src/reportWebVitals.js
  Dhruv/instagram-profile-ui-clone-master/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#89 added instagram ui design
  Samridhi_Yadav/instagram-profile-ui-clone-master/README.md
  Samridhi_Yadav/instagram-profile-ui-clone-master/package-lock.json
  Samridhi_Yadav/instagram-profile-ui-clone-master/package.json
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/favicon.ico
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/index.html
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/logo192.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/logo512.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/manifest.json
  Samridhi_Yadav/instagram-profile-ui-clone-master/public/robots.txt
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/App.css
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/App.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/App.test.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/About.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/Highlights.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/PostGrid.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/Profile.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/ProfileButtons.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/ProfileDetails.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/Tabs.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/TopNav.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/Components/ViewDashboard.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/Grid.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/Guides.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/IGTV.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/Reels.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/Tags.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/highlight1.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/highlight2.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/highlight3.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/highlight4.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/highlight5.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post1.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post2.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post3.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post4.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post5.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post6.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post7.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post8.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/post9.png
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/assets/scLogo.jpg
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/index.css
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/index.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/logo.svg
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/reportWebVitals.js
  Samridhi_Yadav/instagram-profile-ui-clone-master/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#90 added smartwatch ui
  Samridhi_Yadav/SmartWatch-HTML-CSS--master/index.html
  Samridhi_Yadav/SmartWatch-HTML-CSS--master/sparshCodesLogo.png
  Samridhi_Yadav/SmartWatch-HTML-CSS--master/style.css
  Samridhi_Yadav/SmartWatch-HTML-CSS--master/watch-face.webp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#95 added whatsapp ui web page
  Dhruv/whatsapp-ui-clone-main/README.md
  Dhruv/whatsapp-ui-clone-main/package-lock.json
  Dhruv/whatsapp-ui-clone-main/package.json
  Dhruv/whatsapp-ui-clone-main/public/favicon.ico
  Dhruv/whatsapp-ui-clone-main/public/index.html
  Dhruv/whatsapp-ui-clone-main/public/logo192.png
  Dhruv/whatsapp-ui-clone-main/public/logo512.png
  Dhruv/whatsapp-ui-clone-main/public/manifest.json
  Dhruv/whatsapp-ui-clone-main/public/robots.txt
  Dhruv/whatsapp-ui-clone-main/src/App.js
  Dhruv/whatsapp-ui-clone-main/src/App.test.js
  Dhruv/whatsapp-ui-clone-main/src/Components/Chats.js
  Dhruv/whatsapp-ui-clone-main/src/Components/Header.js
  Dhruv/whatsapp-ui-clone-main/src/Components/HeaderTabs.js
  Dhruv/whatsapp-ui-clone-main/src/Components/HeaderTop.js
  Dhruv/whatsapp-ui-clone-main/src/Components/Home.js
  Dhruv/whatsapp-ui-clone-main/src/Components/NewChat.js
  Dhruv/whatsapp-ui-clone-main/src/assets/divine.png
  Dhruv/whatsapp-ui-clone-main/src/assets/elonMusk.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/johnWick.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/kylieJenner.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/loki.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/modi.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/rajKundra.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/rajpalYadav.PNG
  Dhruv/whatsapp-ui-clone-main/src/assets/snoopDog.jpg
  Dhruv/whatsapp-ui-clone-main/src/assets/steveRogers.jpeg
  Dhruv/whatsapp-ui-clone-main/src/index.css
  Dhruv/whatsapp-ui-clone-main/src/index.js
  Dhruv/whatsapp-ui-clone-main/src/reportWebVitals.js
  Dhruv/whatsapp-ui-clone-main/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#99 added whatsapp ui clone
  Samridhi_Yadav/whatsapp-ui-clone-main/README.md
  Samridhi_Yadav/whatsapp-ui-clone-main/package-lock.json
  Samridhi_Yadav/whatsapp-ui-clone-main/package.json
  Samridhi_Yadav/whatsapp-ui-clone-main/public/favicon.ico
  Samridhi_Yadav/whatsapp-ui-clone-main/public/index.html
  Samridhi_Yadav/whatsapp-ui-clone-main/public/logo192.png
  Samridhi_Yadav/whatsapp-ui-clone-main/public/logo512.png
  Samridhi_Yadav/whatsapp-ui-clone-main/public/manifest.json
  Samridhi_Yadav/whatsapp-ui-clone-main/public/robots.txt
  Samridhi_Yadav/whatsapp-ui-clone-main/src/App.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/App.test.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/Chats.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/Header.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/HeaderTabs.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/HeaderTop.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/Home.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/Components/NewChat.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/divine.png
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/elonMusk.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/johnWick.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/kylieJenner.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/loki.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/modi.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/rajKundra.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/rajpalYadav.PNG
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/snoopDog.jpg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/assets/steveRogers.jpeg
  Samridhi_Yadav/whatsapp-ui-clone-main/src/index.css
  Samridhi_Yadav/whatsapp-ui-clone-main/src/index.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/reportWebVitals.js
  Samridhi_Yadav/whatsapp-ui-clone-main/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#104 Added Sudoku Solver
  Elite-Sudoku-Solver_web/index.css
  Elite-Sudoku-Solver_web/index.html
  Elite-Sudoku-Solver_web/index.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#102 Added Emoji Rating Code
  Emoji Rating - WEB PRO/index,js
  Emoji Rating - WEB PRO/index.html
  Emoji Rating - WEB PRO/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#101 stopwatch added
  abhinav web/index.html
  abhinav web/script.js
  abhinav web/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#110 added home page
  site/index/readme.md
  site/index/social-media-dashboard-master/README.md
  site/index/social-media-dashboard-master/images/favicon-32x32.png
  site/index/social-media-dashboard-master/images/icon-down.svg
  site/index/social-media-dashboard-master/images/icon-facebook.svg
  site/index/social-media-dashboard-master/images/icon-instagram.svg
  site/index/social-media-dashboard-master/images/icon-twitter.svg
  site/index/social-media-dashboard-master/images/icon-up.svg
  site/index/social-media-dashboard-master/images/icon-youtube.svg
  site/index/social-media-dashboard-master/index.html
  site/index/social-media-dashboard-master/main.js
  site/index/social-media-dashboard-master/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#106 add file
  vaibhav/index.html
  vaibhav/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#111 added animation
  site/index/loading animation/index.html
  site/index/loading animation/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#115 add watch ui
  site/index/SmartWatch-HTML-CSS--master/index.html
  site/index/SmartWatch-HTML-CSS--master/sparshCodesLogo.png
  site/index/SmartWatch-HTML-CSS--master/style.css
  site/index/SmartWatch-HTML-CSS--master/watch-face.webp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#116 added instagram ui
  site/index/instagram-profile-ui-clone-master/README.md
  site/index/instagram-profile-ui-clone-master/package-lock.json
  site/index/instagram-profile-ui-clone-master/package.json
  site/index/instagram-profile-ui-clone-master/public/favicon.ico
  site/index/instagram-profile-ui-clone-master/public/index.html
  site/index/instagram-profile-ui-clone-master/public/logo192.png
  site/index/instagram-profile-ui-clone-master/public/logo512.png
  site/index/instagram-profile-ui-clone-master/public/manifest.json
  site/index/instagram-profile-ui-clone-master/public/robots.txt
  site/index/instagram-profile-ui-clone-master/src/App.css
  site/index/instagram-profile-ui-clone-master/src/App.js
  site/index/instagram-profile-ui-clone-master/src/App.test.js
  site/index/instagram-profile-ui-clone-master/src/Components/About.js
  site/index/instagram-profile-ui-clone-master/src/Components/Highlights.js
  site/index/instagram-profile-ui-clone-master/src/Components/PostGrid.js
  site/index/instagram-profile-ui-clone-master/src/Components/Profile.js
  site/index/instagram-profile-ui-clone-master/src/Components/ProfileButtons.js
  site/index/instagram-profile-ui-clone-master/src/Components/ProfileDetails.js
  site/index/instagram-profile-ui-clone-master/src/Components/Tabs.js
  site/index/instagram-profile-ui-clone-master/src/Components/TopNav.js
  site/index/instagram-profile-ui-clone-master/src/Components/ViewDashboard.js
  site/index/instagram-profile-ui-clone-master/src/assets/Grid.js
  site/index/instagram-profile-ui-clone-master/src/assets/Guides.js
  site/index/instagram-profile-ui-clone-master/src/assets/IGTV.js
  site/index/instagram-profile-ui-clone-master/src/assets/Reels.js
  site/index/instagram-profile-ui-clone-master/src/assets/Tags.js
  site/index/instagram-profile-ui-clone-master/src/assets/highlight1.png
  site/index/instagram-profile-ui-clone-master/src/assets/highlight2.png
  site/index/instagram-profile-ui-clone-master/src/assets/highlight3.png
  site/index/instagram-profile-ui-clone-master/src/assets/highlight4.png
  site/index/instagram-profile-ui-clone-master/src/assets/highlight5.png
  site/index/instagram-profile-ui-clone-master/src/assets/post1.png
  site/index/instagram-profile-ui-clone-master/src/assets/post2.png
  site/index/instagram-profile-ui-clone-master/src/assets/post3.png
  site/index/instagram-profile-ui-clone-master/src/assets/post4.png
  site/index/instagram-profile-ui-clone-master/src/assets/post5.png
  site/index/instagram-profile-ui-clone-master/src/assets/post6.png
  site/index/instagram-profile-ui-clone-master/src/assets/post7.png
  site/index/instagram-profile-ui-clone-master/src/assets/post8.png
  site/index/instagram-profile-ui-clone-master/src/assets/post9.png
  site/index/instagram-profile-ui-clone-master/src/assets/scLogo.jpg
  site/index/instagram-profile-ui-clone-master/src/index.css
  site/index/instagram-profile-ui-clone-master/src/index.js
  site/index/instagram-profile-ui-clone-master/src/logo.svg
  site/index/instagram-profile-ui-clone-master/src/reportWebVitals.js
  site/index/instagram-profile-ui-clone-master/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#119 added ui clone
  site/index/SmartWatch-HTML-CSS--master/project/readme.md
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/README.md
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/package-lock.json
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/package.json
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/favicon.ico
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/index.html
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/logo192.png
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/logo512.png
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/manifest.json
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/public/robots.txt
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/App.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/App.test.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/Chats.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/Header.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/HeaderTabs.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/HeaderTop.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/Home.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/Components/NewChat.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/divine.png
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/elonMusk.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/johnWick.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/kylieJenner.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/loki.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/modi.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/rajKundra.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/rajpalYadav.PNG
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/snoopDog.jpg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/assets/steveRogers.jpeg
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/index.css
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/index.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/reportWebVitals.js
  site/index/SmartWatch-HTML-CSS--master/project/whatsapp-ui-clone-main/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#123 added blog post
  Sanskriti/blog post/index.html
  Sanskriti/blog post/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#124 added web page
  Sanskriti/webpage/index.html
  Sanskriti/webpage/p.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#130 added bookmark landing page
  khushi/README.md
  khushi/index.html
  khushi/main.js
  khushi/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#126 Dhruv Garg
  Dhruv Garg/Farmer Website/2.jpg
  Dhruv Garg/Farmer Website/DFD Chart.png
  Dhruv Garg/Farmer Website/Flappy Bird/flappy.css
  Dhruv Garg/Farmer Website/Flappy Bird/flappy.html
  Dhruv Garg/Farmer Website/Flappy Bird/flappy.js
  Dhruv Garg/Farmer Website/Flappy Bird/images/bg.png
  Dhruv Garg/Farmer Website/Flappy Bird/images/bird.png
  Dhruv Garg/Farmer Website/Flappy Bird/images/fg.png
  Dhruv Garg/Farmer Website/Flappy Bird/images/pipeNorth.png
  Dhruv Garg/Farmer Website/Flappy Bird/images/pipeSouth.png
  Dhruv Garg/Farmer Website/Flappy Bird/sounds/fly.mp3
  Dhruv Garg/Farmer Website/Flappy Bird/sounds/score.mp3
  Dhruv Garg/Farmer Website/Guava.jpg
  Dhruv Garg/Farmer Website/Home.css
  Dhruv Garg/Farmer Website/Home.html
  Dhruv Garg/Farmer Website/Rice.jpg
  Dhruv Garg/Farmer Website/Service.css
  Dhruv Garg/Farmer Website/Services.html
  Dhruv Garg/Farmer Website/aboutus.css
  Dhruv Garg/Farmer Website/aboutus.html
  Dhruv Garg/Farmer Website/back.jpg
  Dhruv Garg/Farmer Website/banana.jpg
  Dhruv Garg/Farmer Website/help.jpg
  Dhruv Garg/Farmer Website/image.jpg
  Dhruv Garg/Farmer Website/image1.jfif
  Dhruv Garg/Farmer Website/image2.jpg
  Dhruv Garg/Farmer Website/land.jpg
  Dhruv Garg/Farmer Website/login.css
  Dhruv Garg/Farmer Website/login.html
  Dhruv Garg/Farmer Website/login.png
  Dhruv Garg/Farmer Website/mail.png
  Dhruv Garg/Farmer Website/mango.jpg
  Dhruv Garg/Farmer Website/pineapple.jpg
  Dhruv Garg/Farmer Website/signup.css
  Dhruv Garg/Farmer Website/signup.html
  Dhruv Garg/Farmer Website/trust.jpg
  Dhruv Garg/Farmer Website/wheat.jpg
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#134 Tic Tac Toe Game
  Dhruv Garg/Farmer Website/Tic Tac Toe Game/one.css
  Dhruv Garg/Farmer Website/Tic Tac Toe Game/one.html
  Dhruv Garg/Farmer Website/Tic Tac Toe Game/one.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#139 added dice roll
  akarsh dubey/dice_roll_simulator.py
  akarsh dubey/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#140 add emailslicer
  akarsh dubey/emailslicer.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#143 added splash screen
  akarsh dubey/webpage/index.html
  akarsh dubey/webpage/p.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#147 add emailslicer
  shivam/dice_roll_simulator.py
  shivam/emailslicer.py
  shivam/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#148 added emailslicer
  shivam/a/dice_roll_simulator.py
  shivam/a/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#149 added whatsapp clone
  shivam/whatsapp-ui-clone-main/README.md
  shivam/whatsapp-ui-clone-main/package-lock.json
  shivam/whatsapp-ui-clone-main/package.json
  shivam/whatsapp-ui-clone-main/public/favicon.ico
  shivam/whatsapp-ui-clone-main/public/index.html
  shivam/whatsapp-ui-clone-main/public/logo192.png
  shivam/whatsapp-ui-clone-main/public/logo512.png
  shivam/whatsapp-ui-clone-main/public/manifest.json
  shivam/whatsapp-ui-clone-main/public/robots.txt
  shivam/whatsapp-ui-clone-main/src/App.js
  shivam/whatsapp-ui-clone-main/src/App.test.js
  shivam/whatsapp-ui-clone-main/src/Components/Chats.js
  shivam/whatsapp-ui-clone-main/src/Components/Header.js
  shivam/whatsapp-ui-clone-main/src/Components/HeaderTabs.js
  shivam/whatsapp-ui-clone-main/src/Components/HeaderTop.js
  shivam/whatsapp-ui-clone-main/src/Components/Home.js
  shivam/whatsapp-ui-clone-main/src/Components/NewChat.js
  shivam/whatsapp-ui-clone-main/src/assets/divine.png
  shivam/whatsapp-ui-clone-main/src/assets/elonMusk.jpg
  shivam/whatsapp-ui-clone-main/src/assets/johnWick.jpg
  shivam/whatsapp-ui-clone-main/src/assets/kylieJenner.jpg
  shivam/whatsapp-ui-clone-main/src/assets/loki.jpg
  shivam/whatsapp-ui-clone-main/src/assets/modi.jpg
  shivam/whatsapp-ui-clone-main/src/assets/rajKundra.jpg
  shivam/whatsapp-ui-clone-main/src/assets/rajpalYadav.PNG
  shivam/whatsapp-ui-clone-main/src/assets/snoopDog.jpg
  shivam/whatsapp-ui-clone-main/src/assets/steveRogers.jpeg
  shivam/whatsapp-ui-clone-main/src/index.css
  shivam/whatsapp-ui-clone-main/src/index.js
  shivam/whatsapp-ui-clone-main/src/reportWebVitals.js
  shivam/whatsapp-ui-clone-main/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#150 added web page
  shivam/webpage/index.html
  shivam/webpage/p.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#152 added alarm
  sam/alarm.py
  sam/readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#153 added story generator
  sam/storygenerator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#154 added story generator
  reva/readme.md
  reva/storygenerator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#159 added alrm
  reva/alarm.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#160 added rcp game
  reva/rock,paper,scissors_game.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#161 added alarm
  Anmol_Pal/alarm.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#162 added story generator
  Anmol_Pal/storygenerator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#163 added alarm
  Bhavya Tyagi/alarm.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#165 Add files via upload
  CRUD Project/alarm.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#166 Add files via upload
  Bhavya Tyagi/dice_roll_simulator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#167 Add files via upload
  CandyProject/blog post/index.html
  CandyProject/blog post/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
